<Project Sdk="Godot.NET.Sdk/4.7.2">
 <PropertyGroup><TargetFramework>net9.0</TargetFramework><EnableDynamicLoading>true</EnableDynamicLoading><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><LibreKOClientDir Condition="'$(LibreKOClientDir)' == ''">../../build/client/data_LibreKO_windows_x86_64</LibreKOClientDir></PropertyGroup>
 <ItemGroup>
  <Reference Include="LibreKO"><HintPath>$(LibreKOClientDir)/LibreKO.dll</HintPath></Reference>
  <Reference Include="KnightOnlineUiClassic"><HintPath>../bin/KnightOnlineUiClassic.dll</HintPath></Reference>
 </ItemGroup>
</Project>
